name: dsci532
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2.2
  - matplotlib=3.10.6
  - jupyter
  - seaborn
  - shiny
  - pip
  - pip:
    - querychat
    - anthropic
    - python-dotenv
    - gspread
    - google-auth
    - ibis-framework[duckdb]
    - pyarrow
    - pyarrow-hotfix
    - pytest
    - pytest-playwright
    - playwright
